# Generated by Django 4.1 on 2022-10-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=30)),
                ('empage', models.IntegerField()),
                ('empsalary', models.IntegerField()),
            ],
        ),
    ]
